### ISSUE TITLE
Mesh data visualization don't work with multiblock mesh with mayavi2

### ISSUE THREAD

**Issue by khiltunen** [simphony/simphony-mayavi#127]
Trying to visualize mesh made of multiple blocks on OpenFoam. If some module is added in mayavi2 (for example Vectors) Segmentation fault is gained. Using simple one block mesh everything seems to work. Attached are files to reproduce the error

[vortex_shedding.py.txt](https://github.com/simphony/simphony-mayavi/files/100750/vortex_shedding.py.txt)
[vortex_shedding_mesh.py.txt](https://github.com/simphony/simphony-mayavi/files/100749/vortex_shedding_mesh.py.txt)

**Comment by kitchoi** [comment]
Couldn't reproduce it... 
Edit: Here it shows Glyph.  But I just tried all of them.  No Seg fault 
![screenshot from 2016-01-22 16 09 53](https://cloud.githubusercontent.com/assets/3673984/12515913/9b1035cc-c122-11e5-834b-ff6ae1b01b5c.png)

**Comment by khiltunen** [comment]
Tried also glyph. It seems to crash with every module. In poiseuille example if i put directly to code
    s = Surface()
    mayavi.add_module(s) 
it works, put also in that example if i try to add module in mayavi2 it crashes.

With this vortex_shedding case if i add module directly in code, mayavi2 window is shown put its freezed with no control.

**Comment by khiltunen** [comment]
Just to remind my environment is VM ubuntu 12.04LTS and i'm connecting thru vnc.

**Comment by kitchoi** [comment]
And running unittest does not produce Seg Fault like in #111?  The other day I reproduced the Seg Fault by installing paraview in the same virtual environment (and so fixed it by removing simphony-paraview).  Just wondering if that is the case here as well.

**Comment by khiltunen** [comment]
Yes i have simphony-paraview installed. How did you uninstalled it ? Tried easy_install -m simphony-paraview ? Still produces same Seg fault.

**Comment by kitchoi** [comment]
Looks like paraview is interfering.  Try `pip unisntall simphony-paraview` and if you have paraviewopenfoam in your PYTHONPATH and LD_LIBRARY_PATH, remove them too.

**Comment by khiltunen** [comment]
Done that. paraviewopenfoam was not in paths. When i add module in mayavi2 it flashes the visualization for a moment and then crashes with Seg fault.

**Comment by kitchoi** [comment]
Does your VM support OpenGL?  Is it turned on?

**Comment by khiltunen** [comment]
I'm using through vnc and it uses Mesa i suppose

**Comment by kitchoi** [comment]
@khiltunen does this problem persist if you reinstall mayavi after removing paraview?

**Comment by khiltunen** [comment]
I get it to work after removing paraview.

**Comment by kitchoi** [comment]
Thanks!
